export const reportIssueOptions = [
  {
    id: 'fare_payment',
    title: 'Fare or payment issue',
    subtitle: 'Incorrect fare, cash/UPI problem',
    icon: 'wallet',
    heading: 'Fare or payment issue',
    prompt: 'Tell us what happened with the fare or payment.',
    subReasons: [
      { id: 'fare_incorrect', label: 'Fare seems incorrect' },
      { id: 'payment_not_received', label: 'Payment not received' },
      { id: 'different_amount', label: 'Rider paid different amount' },
      { id: 'transaction_issue', label: 'Cash/UPI transaction issue' },
      { id: 'other_fare_issue', label: 'Other' },
    ],
  },
  {
    id: 'rider_issue',
    title: 'Rider issue',
    subtitle: 'Rider behavior or trip-related problem',
    icon: 'rider',
    heading: 'Rider issue',
    prompt: 'Tell us what happened with the rider.',
    subReasons: [
      { id: 'rider_rude', label: 'Rider was rude or disrespectful' },
      { id: 'rider_damage', label: 'Rider caused vehicle mess or damage' },
      { id: 'rider_intoxicated', label: 'Rider appeared intoxicated' },
      { id: 'rider_refused_exit', label: 'Rider refused to exit' },
      { id: 'other_rider_issue', label: 'Other' },
    ],
  },
  {
    id: 'lost_item',
    title: 'Lost item',
    subtitle: 'Something was left in the vehicle',
    icon: 'lost_item',
    heading: 'Lost item in vehicle',
    prompt: 'What type of item was left behind?',
    subReasons: [
      { id: 'phone_electronics', label: 'Phone or electronic device' },
      { id: 'wallet_bag', label: 'Wallet, purse or bag' },
      { id: 'clothing_accessory', label: 'Clothing, jacket or glasses' },
      { id: 'keys_documents', label: 'Keys or personal documents' },
      { id: 'other_lost_item', label: 'Other item' },
    ],
  },
  {
    id: 'trip_details',
    title: 'Trip details are incorrect',
    subtitle: 'Wrong pickup, drop, distance or trip info',
    icon: 'document',
    heading: 'Trip details incorrect',
    prompt: 'What information was incorrect about this trip?',
    subReasons: [
      { id: 'wrong_pickup', label: 'Pickup address was wrong' },
      { id: 'wrong_drop', label: 'Drop location was wrong' },
      { id: 'wrong_distance_time', label: 'Trip distance or duration was inaccurate' },
      { id: 'wrong_route', label: 'Route recorded incorrectly' },
      { id: 'other_trip_details', label: 'Other' },
    ],
  },
  {
    id: 'vehicle_issue',
    title: 'Vehicle issue',
    subtitle: 'Problem with the vehicle during the trip',
    icon: 'vehicle',
    heading: 'Vehicle issue',
    prompt: 'What happened with your vehicle?',
    subReasons: [
      { id: 'flat_tyre', label: 'Flat tyre or puncture' },
      { id: 'mechanical_breakdown', label: 'Engine or mechanical failure' },
      { id: 'battery_fuel', label: 'Fuel or battery issue' },
      { id: 'ac_comfort', label: 'AC or cooling issue' },
      { id: 'other_vehicle_issue', label: 'Other' },
    ],
  },
  {
    id: 'safety_concern',
    title: 'Safety concern',
    subtitle: 'Report a safety-related incident',
    icon: 'safety',
    isSafety: true,
    heading: 'Safety concern',
    prompt: 'If you are in immediate danger, please use the safety features below.',
    subReasons: [
      { id: 'safety_rider_behavior', label: 'Rider behavior issue' },
      { id: 'safety_harassment', label: 'Harassment' },
      { id: 'safety_unsafe', label: 'Felt unsafe during the trip' },
      { id: 'safety_accident', label: 'Accident or collision' },
      { id: 'safety_other', label: 'Other' },
    ],
  },
  {
    id: 'something_else',
    title: 'Something else',
    subtitle: 'Tell us what happened',
    icon: 'dots',
    directToDetails: true,
    heading: 'Something else',
    prompt: 'Tell us what happened.',
    subReasons: [],
  },
];
